name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Node.js version
        run: |
          node -v | grep -E "^v(1[8-9]|[2-9][0-9])" || exit 1

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format
